services:
   # frontend:
    #  build: ./frontend
       # ports:
       #   - "3000:3000"
       # networks:
       #   - placeport
    
  backend:
    build: ./backend
    ports: 
      - "5000:5000"
    networks:
      - placeport
    env_file:
      - ./backend/.env
  
networks:
    placeport:
      driver: bridge
